// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agffvistnpmohlvnysbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZmZ2aXN0bnBtb2hsdm55c2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzUxMDUsImV4cCI6MjA1NjkxMTEwNX0.1IuozCNaJxDYeVh2B4cQMzFTh-4muzjWABA_Hz5b-8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);